COMMENT = GNU gettext utilities
MAINTAINER = OpenBSD Ports <ports@openbsd.org>
HOMEPAGE = https://www.gnu.org/software/gettext/

DISTNAME = gettext-0.22.8
PKGNAME = ${DISTNAME}
FULLPKGNAME = ${PKGNAME}