# frozen_string_literal: true

require "open3"

module Master
  module Fix
    class FixLoop
      class FileCollector
        # Exclusion is Scanner's, not ours.
        #
        # This class used to carry its own SKIP_DIRS list, a strict subset of
        # the scanner's, and the gap was not academic: Scanner::SKIP_RELATIVE_PATHS
        # names web/public/three.face.module.js, face.runtime.js and the two
        # face bundles precisely because they are generated or vendored, and
        # /scan honoured that while /fix did not. So `/fix .` proposed 2954
        # violations against a minified THREE build and 931 against a file whose
        # first line reads "Generated by rails assets:build_face_runtime -- do
        # not edit by hand", plus 798 against reports/, which scan skips as
        # generated output. Two lists, one of them wrong, and the wrong one held
        # the write end.
        #
        # A file that must not be edited is not a file worth collecting for a
        # fix pass, so there is one list now and the scanner owns it.
        attr_reader :skipped

        def initialize(root:, bus: nil)
          @root = root
          @bus = bus
          @skipped = 0
        end

        def collect(target)
          tracked = collect_tracked(target)
          return tracked unless tracked.empty?

          candidates = Dir.glob(File.join(target, "**", "*")).select { |f| File.file?(f) }
          retain(candidates)
        end

        def collect_changed(target)
          changed = changed_since_last_commit(target)
          return collect(target) if changed.empty?
          changed
        rescue StandardError => e
          @bus&.publish("fix_loop:incremental_fallback", error: e.message)
          collect(target)
        end

        def mtimes(files)
          files.to_h { |path| [path, File.exist?(path) ? File.mtime(path).to_f : nil] }
        end

        def quiescent?(files, before)
          mtimes(files) == before
        rescue StandardError => e
          Master::Ground::Swallow.log(e, context: "FileCollector.quiescent?")
          false
        end

        private

        def collect_tracked(target)
          out, _, status = Master::Io::Exec.capture3("git", "-C", @root, "ls-files", "-z")
          return [] unless status.success?

          tracked = out.split("\0").map { |rel| File.join(@root, rel) }
                       .select { |file| File.file?(file) && under_path?(file, target) }
          retain(tracked)
        rescue StandardError => e
          Master::Ground::Swallow.log(e, context: "FileCollector.collect_tracked")
          []
        end

        def changed_since_last_commit(target)
          out, _, status = Master::Io::Exec.capture3("git", "-C", @root, "diff", "--name-only", "HEAD")
          return [] unless status.success?

          out.lines.map(&:strip).reject(&:empty?)
             .map { |rel| File.join(@root, rel) }
             .select { |f| File.exist?(f) && f.start_with?(target) }
             .then { |files| retain(files) }
        end

        # Counted and published rather than quietly dropped — a fix pass that
        # silently narrows its own input reads as "nothing left to do".
        def retain(files)
          kept, dropped = files.partition { |file| !skipped?(file) }
          @skipped = dropped.size
          @bus&.publish("fix_loop:skipped", count: dropped.size, sample: dropped.first(5).map { |f| relative(f) }) if dropped.any?
          kept.sort
        end

        def skipped?(path)
          Master::Review::Scan::Scanner.skip_path?(path, root: @root) || binary?(path)
        end

        def relative(path)
          path.to_s.delete_prefix("#{@root}#{File::SEPARATOR}")
        end

        def binary?(path)
          File.file?(path) && Master.binary_file?(path)
        rescue StandardError
          true
        end

        def under_path?(path, root)
          exp = File.expand_path(path)
          exp_root = File.expand_path(root)
          exp == exp_root || exp.start_with?("#{exp_root}#{File::SEPARATOR}")
        end
      end
    end
  end
end
