# frozen_string_literal: true

namespace :assets do
  desc "Build public/face.runtime.js from face.part*.txt (skips blob assembly in browser)"
  task build_face_runtime: :environment do
    out = Rails.root.join("public/face.runtime.js")
    segments = (1..3).map { |part| Rails.root.join("public", "face.part#{part}.txt") }
    segments << Rails.root.join("public", "face_speech_runtime.js")
    segments << Rails.root.join("public", "face_speech_playback.js")
    segments << Rails.root.join("public", "face.part5.txt")
    source = segments.map do |path|
      raise "missing #{path}" unless File.file?(path)

      File.read(path)
    end.join("\n")

    banner = <<~JS
      // Generated by rails assets:build_face_runtime — do not edit by hand.
      // Import map + MASTER_ASSET_PATHS resolve tail module imports at runtime.
    JS

    File.write(out, "#{banner}#{source}\n")
    puts "wrote #{out} (#{File.size(out)} bytes)"
  end
end

if Rake::Task.task_defined?("assets:precompile")
  Rake::Task["assets:precompile"].enhance(["assets:build_face_runtime"])
end
