#!/bin/sh
set -eu
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PUB="$ROOT/public"
OUT="$PUB/face_vision.bundle.js"
{
  echo "// Generated by script/build_face_vision.sh — do not edit by hand."
  for part in face_vision_core.js face_vision_a.js face_vision_b.js face_vision_c.js face_vision_d.js; do
    path="$PUB/$part"
    test -f "$path" || { echo "missing $path" >&2; exit 1; }
    cat "$path"
    echo ""
  done
} > "$OUT"
RAW=$(wc -c < "$OUT" | tr -d ' ')
GZ=$(gzip -c "$OUT" | wc -c | tr -d ' ')
echo "face_vision.bundle.js raw=${RAW} gzip=${GZ}"
