COMMENT = distributed version control
MAINTAINER = OpenBSD Ports <ports@openbsd.org>
HOMEPAGE = https://git-scm.com/

DISTNAME = git-2.43.0
PKGNAME = ${DISTNAME}
FULLPKGNAME = ${PKGNAME}

BUILD_DEPENDS = devel/gettext
RUN_DEPENDS = devel/gettext
LIB_DEPENDS = security/openssl

PERMIT_PACKAGE_CDROM_DISTFILES = Yes