# frozen_string_literal: true

require "net/http"
require "uri"

module Ports
  module Openbsd
    # Fetches the package index over HTTPS.
    #
    # Replaces FtpIndexFetcher's target, which could not have worked: it asked
    # for ftp://ftp.openbsd.org/pub/OpenBSD/ports/<category>/INDEX, and measured
    # on 2026-08-05 that path is a 404 on the mirror (no ports/ directory exists
    # at the top level at all) while plain FTP to the host times out. The
    # per-category pipe-delimited INDEX that IndexParser expects is generated by
    # `make index` inside a ports tree; it is not published anywhere.
    class PackageIndexFetcher
      DEFAULT_BASE = "https://cdn.openbsd.org/pub/OpenBSD"
      DEFAULT_ARCH = "amd64"
      OPEN_TIMEOUT = 15
      READ_TIMEOUT = 60

      def initialize(platform:, base: nil, arch: nil, release: nil)
        @platform = platform
        @base = (base || ENV["BSDPORTS_MIRROR"] || https_base_for(platform)).chomp("/")
        @arch = arch || ENV.fetch("BSDPORTS_ARCH", DEFAULT_ARCH)
        @release = release || ENV["BSDPORTS_RELEASE"]
      end

      attr_reader :platform, :base, :arch

      # Newest numeric release directory on the mirror. Pinned by
      # BSDPORTS_RELEASE when an operator wants a specific one.
      def release
        @release ||= begin
          listing = get("#{base}/")
          releases = listing.to_s.scan(%r{href="(\d+\.\d+)/"}).flatten
          raise "no release directories at #{base}/" if releases.empty?

          releases.max_by { |r| r.split(".").map(&:to_i) }
        end
      end

      def index_url = "#{base}/#{release}/packages/#{arch}/index.txt"

      # Yields an IO of the index. Returns nil and logs when the mirror cannot
      # be reached — the caller decides whether that is fatal.
      def each_entry
        body = get(index_url)
        return nil if body.nil?

        Ports::Openbsd::PackageIndexParser.parse(StringIO.new(body))
      rescue StandardError => e
        Rails.logger.warn("bsdports package index fetch failed url=#{index_url} error=#{e.class}: #{e.message}")
        nil
      end

      private

      # Platform.mirror_url is an ftp:// URL kept for provenance; the same host
      # path serves over HTTPS, which is what OpenBSD mirrors actually offer.
      def https_base_for(platform)
        url = platform.mirror_url.to_s
        return DEFAULT_BASE if url.blank?

        url.sub(%r{\Aftp://}, "https://")
      end

      def get(url, limit: 3)
        raise "too many redirects for #{url}" if limit.zero?

        uri = URI.parse(url)
        response = Net::HTTP.start(uri.host, uri.port, use_ssl: uri.scheme == "https",
                                                       open_timeout: OPEN_TIMEOUT, read_timeout: READ_TIMEOUT) do |http|
          http.get(uri.request_uri)
        end

        case response
        when Net::HTTPSuccess then response.body
        when Net::HTTPRedirection then get(URI.join(url, response["location"]).to_s, limit: limit - 1)
        else
          Rails.logger.warn("bsdports mirror #{url} returned #{response.code}")
          nil
        end
      end
    end
  end
end
