development:
  adapter: async

test:
  adapter: test

production:
  adapter: solid_cable
  connects_to:
    database:
      writing: cable
  polling_interval: <%= ENV.fetch("CABLE_POLLING_INTERVAL", "0.25").to_f.seconds %>
  message_retention: 1.day
